### ISSUE TITLE
Add https listener

### ISSUE THREAD

**Issue by KodoGit** [MarcelCoding/jitsi-openid#214]
Hello. Thx for this adapter!
I think that readme needs some notice about SSL implementation. Like "don't forget to cover it in reverse proxy with SSL".
And may be you could add native SSL support like they did for Jitsi itself. Two env variables for keys would be nice.
And thx again ^)

**Comment by MarcelCoding** [comment]
IDK, about this. I only know it that you are using a reverse proxy, especially, because you want to deploy multiple services under the same IP address and port. Therefore, I don't see any meaningful sense in adding HTTPS listener support. If you have any other argument, feed free to prove me different.

I've addressed all your other issues and created a new release.

**Comment by KodoGit** [comment]
Zero trust communication policy assumes all connections should be secured. This app needs to be exposed as Jitsi redirects user browser to it. And all modern browsers deprecated support for an unsecured HTTP. So without native HTTPS support it needs to be wrapped into reverse proxy now.

**Comment by MarcelCoding** [comment]
Ok, that's a valid points where I totally agree, but I meant this, regarding now using a reverse proxy. So why jitsi openid should support listening on https directly. I think a reverse proxy is totally valid to use.
